version: '2'
services:
  web:
    user: "$UID:$GID"
    build: .
    volumes:
     - ./mdbook:/mdbook
    ports:
      - "$PORT:3000"
    command: >
      bash -c '
      test -e book.toml || mdbook init;
      mdbook serve -n 0.0.0.0 -p 3000
      '
